// Quiz
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const QUIZ_SET_ANSWER_STATUS = 'QUIZ_SET_ANSWER_STATUS';
export const QUIZ_IS_FINISHED = 'QUIZ_IS_FINISHED';
export const QUIZ_SET_ACTIVE_QUESTION = 'QUIZ_SET_ACTIVE_QUESTION';
export const QUIZ_REPEAT = 'QUIZ_REPEAT';

// QuizList
export const FETCH_QUIZES_START = 'FETCH_QUIZES_START';
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS';
export const FETCH_QUIZES_FAILED = 'FETCH_QUIZES_FAILED';

// QuizCreator
export const ADD_QUESTION_QUIZ = 'ADD_QUESTION_QUIZ';
export const RESET_QUIZ_CREATION = 'RESET_QUIZ_CREATION';
export const QUIZ_CREATION_FAILED = 'QUIZ_CREATION_FAILED';

// Auth
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';